blank_issues_enabled: false
contact_links:
  - name: ğŸŒ My Discord Server
    url: https://discord.gg/cMGhNtZ3tW
    about: Join my personal Discord server where you can post messages in the plugin channels or message me directly. This is often easier and quicker than creating an issue on here.
